apps/scroll-cd/README.md
=> feat(challenge12): add embedded video

apps/ngrx-notification/src/app/app.config.ts, apps/ngrx-notification/src/main.ts
Due to upgrading to Angular 16,  `REDUCERS` were in the incorrect file and should have been moved to `app.config.ts` from `main.ts`.
Not 100% sure the code is still working as intended, but it seems to be.
=> fix(ngrx-notification): compilation error

docs/src/content/docs/guides/checkout-answer.md, docs/src/content/docs/guides/create-challenge.md, docs/src/content/docs/guides/getting-started.md, docs/src/content/docs/guides/resolve-challenge.md
Fixed some typos found in the docs.
=> docs: typos found in documentation page

docs/astro.config.mjs
Wrong url in the navigation bar
=> Docs: Update github url

docs/src/content/docs/challenges/angular-performance/36-ngfor-optimize.md, libs/cli/src/generators/challenge/files/docs/__challengeNumber__-__projectName__.md__tmpl__, libs/cli/src/generators/challenge/files/readme/README.md__tmpl__, libs/cli/src/generators/challenge/generator.ts
updated the start command from 
`npx nx serve ngfor-optimize` to
`npx nx serve performance-ngfor-optimize`
=> docs: update start command

docs/src/content/docs/challenges/testing/28-checkbox.md
The links were broken so I investigated and challenge number was wrong.
=> fix: checkbox challenge number

docs/src/content/docs/challenges/angular/1-projection.md
This PR fixed constraints section for angular challenge ["Projection"](https://angular-challenges.vercel.app/challenges/angular/1-projection/)
[#238](https://github.com/tomalaforge/angular-challenges/issues/238)
=> Fix: update 1-projection.md description

docs/src/content/docs/challenges/angular/39-injection-token.md
I think your article 'stop being scared of injection tokens' should be added either as a hint or as a blogLink to the injection token docs.
=> docs: injection token blogLink

docs/src/content/docs/guides/getting-started.md
Typo in getting started guide #257
resolved.
=> resolving Typo in getting started guide

docs/src/content/docs/challenges/angular/1-projection.md, docs/src/content/docs/challenges/angular/10-pipe-utility.md, docs/src/content/docs/challenges/angular/8-pipe-pure.md, docs/src/content/docs/challenges/angular/9-pipe-wrapFn.md, docs/src/content/docs/challenges/rxjs/11-bug-chaining-operator.md, docs/src/content/docs/guides/contribute.md, docs/src/content/docs/guides/faq.md, docs/src/content/docs/guides/resolve-challenge.md
I did a little rewording on the pipes section.  
I changed exercice to exercise at one point.   Both are valid.  I reverted it back to stay consistent.
=> fix: various typos

docs/src/components/ActionButtonFooter.astro, docs/src/content/docs/challenges/angular/22-router-input.md, docs/src/content/docs/challenges/angular/33-decoupling.md, docs/src/content/docs/challenges/angular/4-context-outlet-typed.md, docs/src/content/docs/challenges/angular/5-crud.md, docs/src/content/docs/challenges/ngrx/2-effect-selector.md, docs/src/content/docs/challenges/ngrx/7-power-effect.md, docs/src/content/docs/challenges/performance/37-ngfor-biglist.md, docs/src/content/docs/challenges/testing/19-input-output.md, docs/src/content/docs/challenges/testing/20-modal.md, docs/src/content/docs/challenges/testing/23-harness.md, docs/src/content/docs/challenges/testing/24-harness-creation.md, docs/src/content/docs/index.mdx
There was a typo for styling - write instead of white.  
Sidenote: I think that styling is still overwritten so the sponsor text is still not white on light mode.
=> fix: more typos

apps/performance/christmas-web-worker/src/app/heavy-calculation.service.ts
=> fix: calculation spelling

docs/src/content/docs/challenges/performance/40-christmas-web-worker.md
May be best to add a hint that you need to use npx to generate the web worker.  
Sidenotes:  
- You are missing a link on line 22. 
- `First, create a web worker using the schematics, then move the issuing function.`  
If you pick the regular angular schematic, the web worker conditional boilerplate is not added to the app component.   The conditional is added when you use the nx schematic.   Add as hint to the readme to pick the nx schematic ?
Are you supposed to have the progress percentage update or not?
=> docs: clarify command

docs/src/content/docs/challenges/performance/40-christmas-web-worker.md
=> fix: typo & add link for calendar

.gitignore, .vscode/settings.json, docs/src/content/docs/es/challenges/angular/3-directive-enhancement.md, docs/src/content/docs/es/challenges/angular/4-context-outlet-typed.md, docs/src/content/docs/es/challenges/angular/5-crud.md, docs/src/content/docs/es/challenges/angular/6-permissions.md
Added to ES-LA translations for Angular Exercises 3,4,5 and 6.
=>  docs: translated to ES-LA exercises 3,4,5 and 6

docs/src/content/docs/es/challenges/angular/10-pipe-utility.md, docs/src/content/docs/es/challenges/angular/13-styling.md, docs/src/content/docs/es/challenges/angular/8-pipe-pure.md, docs/src/content/docs/es/challenges/angular/9-pipe-wrapFn.md
=> docs: exercises 8,9,10,13 in ES-LA

apps/angular/interop-rxjs-signal/src/app/list/photos.component.ts
The placeholder text 'write an article' makes no sense.
=> fix: change placeholder text

docs/src/content/docs/pt/challenges/angular/21-achor-scrolling.md, docs/src/content/docs/pt/challenges/angular/22-router-input.md, docs/src/content/i18n/pt.json
Add translation for challenges 21 (_Anchor Navigation_) and 22 (_@RouterInput()_). Also, create JSON file for PT i18n schema.
=> docs(pt): add more challenge transations and ui i18n schema

apps/ngrx/notification/src/app/data-access/http.service.ts, libs/ngrx-notification/backend/src/lib/fake-backend.service.ts
Typo didn't block functionality.
=> fix: schools typo

libs/ngrx-notification/model/src/lib/school.model.ts
Mirror the same way the other models were named.
=> fix: model consistency

apps/ngrx/notification/src/app/routes.ts
Don't think home route should be lazy loaded.  Step 3 directions implied the root route is not lazy loaded as well.
=> fix: home route not lazy loaded

apps/angular/permissions/src/app/login.component.ts
The header's classes order was changed by prettier.
=> fix(challenge-6): change text for everyone button and remove whitespace in button class

docs/src/content/docs/es/challenges/angular/16-di.md, docs/src/content/docs/es/challenges/angular/21-achor-scrolling.md, docs/src/content/docs/es/challenges/angular/30-interop-rxjs-signal.md, docs/src/content/docs/es/challenges/angular/31-module-to-standalone.md, docs/src/content/docs/es/challenges/angular/32-bug-cd.md, docs/src/content/docs/es/challenges/angular/33-decoupling.md
this PR completes the angular documentation in Spanish
=> feat: adding spanish translations on exercises 16,21,30,31,32. 

docs/src/content/docs/pt/challenges/angular/31-module-to-standalone.md
=> docs(pt): translate challenge 31

apps/angular/interop-rxjs-signal/src/app/photo.model.ts, apps/angular/interop-rxjs-signal/src/app/photos.service.ts
Check the api response.  A lot of properties aren't used but this matches the response better.
=> fix: update interfaces

docs/src/content/docs/challenges/ngrx/7-power-effect.md
You could punch this up even more but I think this is much better explanation of the challenge. 
This would close my issue as well.  
Would still need a PR to touch up the comments inside the challenge code.
=> docs: notification readme rework

apps/ngrx/notification/src/app/app.actions.ts, apps/ngrx/notification/src/app/data-access/notification.service.ts, apps/ngrx/notification/src/app/school/school.store.ts
These comments help improve the challenge.
=> docs: ngrx notification comments

docs/src/content/docs/pt/challenges/angular/32-bug-cd.md
=> docs(pt): translate challenge 32

docs/src/content/docs/es/index.mdx, docs/src/content/docs/fr/index.mdx, docs/src/content/docs/pt/index.mdx
=> docs: update homepage challenges counting and link to latest challenge

docs/src/content/docs/pt/challenges/angular/8-pipe-pure.md
=> docs(pt): translate challenge 8

docs/src/content/docs/pt/challenges/angular/43-signal-input.md, docs/src/content/docs/pt/challenges/angular/44-view-transition.md
And remove "New" badge from challenge 43 which is about `Signal Input`.
=> docs(pt): translate challenge 44

docs/src/content/docs/challenges/angular/44-view-transition.md
I recommend [Quillbot](https://quillbot.com/)  to check grammar etc.
=> fix: view transition typos

docs/src/content/docs/challenges/angular/10-pipe-utility.md, docs/src/content/docs/challenges/angular/22-router-input.md, docs/src/content/docs/challenges/angular/3-directive-enhancement.md, docs/src/content/docs/challenges/angular/4-context-outlet-typed.md, docs/src/content/docs/challenges/angular/5-crud.md, docs/src/content/docs/challenges/angular/8-pipe-pure.md, docs/src/content/docs/challenges/angular/9-pipe-wrapFn.md, docs/src/content/docs/challenges/ngrx/2-effect-selector.md
it seems like exercice is french 😄 changed all occurrences of "exercice" to "exercise"
=> docs: fix exercice typo in docs french to english

docs/src/content/docs/challenges/angular/45-react-in-angular.md
Captialized React and Angular and fixed the `into` typo.  
Initially split bash command, but it is fine as one command.
=> fix: typos in react md

45-react-in-angular.md
=> docs(pt): translate challenge 45

docs/src/content/docs/challenges/angular/6-permissions.md
Updated the article content of this challenge while resolving it.
- Added information links for route guards
- Added missing period
- Changed spelling
=> docs(permissions): update article content

docs/src/content/docs/challenges/testing/19-input-output.md, docs/src/content/docs/challenges/testing/20-modal.md, docs/src/content/docs/challenges/testing/23-harness.md, docs/src/content/docs/challenges/testing/29-real-application.md
- `Statement:` title with colon suffix doesn't follow conventions, changed to `Statement`
- Added `Information` title
- Added harness definition preface
=> docs(testing-harness): update content

docs/src/content/docs/challenges/angular/46-simple-animations.md
As discussed during the creation of this challenge, updated the solution preview videos.
=> docs(simple-animations): update solution previews

apps/typescript/enums-vs-union-types/README.md
=> fix: author in enum Readme.md

docs/src/components/SubscriptionForm.astro, docs/src/content/docs/challenges/testing/23-harness.md, docs/src/content/docs/index.mdx, docs/src/styles/custom-css.css
- Added hover styling for following buttons in landing page
- Get Started
- Go to the latest Challenge
- Give a star
- Sponsor the Project (in footer)
- Added hover styling for buttons in content pages (e. g. challenge page) in the right sidebar
- Email subscription
- Give a star
- Sponsor
- Added hover styling for buttons in article footer
- Community solutions*
- Author's solution
- Article
- ...
On the angular challenges landing page is a subscribe button, which i fixed a week ago or so - font color in dark mode wasn't updated to white.
I noticed that there is a button hover styling on the subscribe button but not on other similar buttons. So i added a hover styling for the similar buttons and fixed the hover styling of the subscribe button.
=> Style button hover

docs/src/content/docs/challenges/angular/4-context-outlet-typed.md
After solving this challenge i've updated the docs a little bit. Added a link to your article in the docs, even it's declared below, because I didn't noticed the article button below - only when I finished the task 😄
=> docs(context-outlet-typed): update content

docs/src/content/docs/guides/contribute.md
I removed `or English mistakes` since there are multiple translations now.
=> fix: contribute page typos

apps/performance/default-onpush/src/app/person-list.component.ts
Quick fix to remove lint warning.
=> refactor: add typing and remove deprecated keycode method

tools/eslint-rules/rules/forbidden-enum.README.md
This is the only? challenge where you don't have anything to serve.
=> docs: remove script in forbidden-enum readme

docs/src/content/docs/fr/guides/checkout-answer.md, docs/src/content/docs/fr/guides/contribute.md, docs/src/content/docs/fr/guides/create-challenge.md, docs/src/content/docs/fr/guides/faq.md, docs/src/content/docs/fr/guides/rebase.md
This PR add french translations for each missing page in "Guides" section : 
* Check out Somebody's Answer
* Contribute
* Create you own challenge
* Rebase your branch
* FAQ
=> docs(fr): add french translation for pages in guides section

docs/src/content/docs/fr/challenges/angular/1-projection.md, docs/src/content/docs/fr/challenges/angular/21-anchor-navigation.md, docs/src/content/docs/fr/challenges/angular/22-router-input.md, docs/src/content/docs/fr/challenges/angular/31-module-to-standalone.md, docs/src/content/docs/fr/challenges/angular/46-simple-animations.md, docs/src/content/docs/fr/challenges/angular/5-crud-application.md, docs/src/content/docs/fr/challenges/angular/8-pure-pipe.md
This PR add french translations for easy "Angular" challenges : 
* Projection
* Crud Application
* Pure Pipe
* Anchor Navigation
* @RouterInput()
* Module to Standalone
* Simple Animations
=> docs(fr): add french translations for easy angular challenges

docs/src/components/Hero.astro
=> fix: color of heart icon in light mode

docs/src/content/docs/challenges/nx/26-generator-comp.md
=> fix: update filename in explanation

docs/src/components/github/SignUp.svelte
=> fix: dark-light-mode-button-icon-github

apps/angular/52-lazy-load-component/README.md
=> fix: lazy load author

apps/signal/54-pipe-observable-to-signal/src/app/currency.service.ts, docs/src/content/docs/challenges/signal/54-pipe-observable-to-signal.md
Also, add a bit more explanation
=> fix: typos in adjectives

README.md
I don't know if you'd want to change this to `50+` so you don't have to continually update this.
=> docs: update challenge count on main readme

apps/signal/56-forms-and-signal/src/app/order.component.ts
Small change to fix a typo in a new challenge
=> fix: correct a typo

docs/src/content/docs/challenges/angular/1-projection.md, docs/src/content/docs/challenges/ngrx/2-effect-selector.md, docs/src/content/docs/es/challenges/angular/1-projection.md, docs/src/content/docs/fr/challenges/angular/1-projection.md, docs/src/content/docs/pt/challenges/angular/1-projection.md, docs/src/content/docs/ru/challenges/angular/1-projection.md, docs/src/content/docs/zh-cn/challenges/angular/1-projection.md
=> Challenge 2 es video

docs/src/content/docs/challenges/angular/1-projection.md
I think it's good idea to add info in description from newest documentation as well.
=> docs: add new docs to 1-projection

apps/signal/43-signal-input/README.md
=> Fix challenge url (Challenge 43 - signal input)

apps/angular/59-content-projection-defer/src/app/page-2.ts
=> fix(59): typo

docs/src/content/docs/challenges/rxjs/14-race-condition.md
Fix typo in docs for Challenge 14
=> Challenge 14 Docs: fix run test command
