tomalaforge/angular-challenges

apps/ngrx-1/README.md, apps/ngrx-1/src/app/app.config.ts, apps/ngrx-1/src/main.ts
_Not sure if you are accepting bug fixes_
Due to a recent refactor of upgrading to Angular v16, the reducers weren't copied over to the new `app.config.ts` file for the `ngrx-1` module.
Also fixed a minor spelling mistake in the related README.md file.
=> fix(ngrx-1): reducers missing from config

apps/performance/ngfor-biglist/project.json
Suppress the warning in the console when you serve the app.
=> fix: biglist seedrandom commonjs dependency

apps/performance/ngfor-biglist/project.json
No real styling in the challenge but you get the warning in the console.
=> fix: biglist angular material styling added

apps/angular/injection-token/src/app/phone.component.ts, apps/angular/injection-token/src/app/video.component.ts
Without selectors, angular can't tell the components apart - name collision warning in console.
=> fix: add selectors for phone & video

apps/angular/bug-cd/README.md, apps/angular/context-outlet-type/README.md, apps/angular/crud/README.md, apps/angular/decoupling/README.md, apps/angular/di/README.md, apps/angular/interop-rxjs-signal/README.md, apps/angular/module-to-standalone/README.md, apps/angular/permissions/README.md, apps/angular/projection/README.md, apps/angular/router-input/README.md, apps/angular/styling/README.md
- Corrected typos in URLs that were leading to 404 pages.
- This PR resolves the typos, redirecting users to the correct documentation page at (https://angular-challenges.vercel.app/).
=> fix(doc): correct typos in documentation URLs for multiple apps

docs/astro.config.mjs, docs/src/content/docs/es/challenges/angular/1-projection.md, docs/src/content/docs/es/challenges/angular/39-injection-token.md, docs/src/content/docs/es/guides/checkout-answer.md, docs/src/content/docs/es/guides/contribute.md, docs/src/content/docs/es/guides/create-challenge.md, docs/src/content/docs/es/guides/faq.md, docs/src/content/docs/es/guides/getting-started.md, docs/src/content/docs/es/guides/rebase.md, docs/src/content/docs/es/guides/resolve-challenge.md, docs/src/content/docs/es/index.mdx
This PR adds internationalization to the docs site and adds Spanish as the first option for an additional language. 
Internationalization is added following the guidelines on the Starlight official docs. I added a root locale (english) so all links continue to work as they do now. This just sets up everything so additional languages can be added. 
As a part of this work, I translated the main page to Spanish as well as all the guide sections and 2 angular challenges. I can work on the rest of the translations for Spanish if you decide to go forward with this. Please feel free to decline this PR if you decide not to go in this direction, it is completely fine and understandable too.
Starlight is awesome in the sense that untranslated pages will fall back to the English ones so this should …
=> feat(docs): add internationalization and add spanish lang

apps/testing/harness/src/app/child.component.spec.ts
- There was a typo & grammar mistake in '**apps/testing/harness/src/app/child.component.spec.ts**' file.
- Changed '**When disabled chebkbox is toggle**' to '**When disabled checkbox is toggled**'.
=> fix: correct typo & grammar in test's name

docs/src/styles/custom-css.css
Had trouble getting astro's preview command to work.
There was an typescript config strict error.  
The note and reminder are not visible on light mode.  I checked the preview seems like nothing else was broken deleting that css.
=> fix: note & reminder visible on light mode

docs/src/content/docs/es/challenges/angular/22-router-input.md, docs/src/content/docs/es/challenges/performance/12-scroll-cd.md, docs/src/content/docs/es/challenges/performance/34-default-onpush.md, docs/src/content/docs/es/challenges/performance/35-memoize.md, docs/src/content/docs/es/challenges/performance/36-ngfor-optimize.md, docs/src/content/docs/es/challenges/performance/37-ngfor-biglist.md, docs/src/content/docs/es/challenges/performance/index.mdx
- Translate pending challenges in the `Angular` section to Spanish (only the ones without the note on top)
- Translate all pages under the `Performace` section to Spanish
=> feat(docs): translate performance section pages to spanish

apps/ngrx/effect-selector/src/app/store/activity/activity.actions.ts, apps/ngrx/effect-selector/src/app/store/user/user.actions.ts
`any` gives an eslint warning.  
Changed the spelling of the action text to match the variable name.  
`loadActivities` is attributed to the AppComponent ?
=> fix: effect selector typos

apps/ngrx/notification/project.json
You need a core theme otherwise snackbar styling is off.
=> fix: angular material core theme added

apps/ngrx/notification/src/app/app.config.ts
Without provideAnimations, snackbar won't display.  This should be it.
=> fix: provideAnimations needed for snackbar

docs/src/content/docs/challenges/angular/3-directive-enhancement.md
Also remove whitespaces before colons and add code highlight on word 'ng-container'
=> docs(en): fit typo

docs/src/content/docs/challenges/angular/1-projection.md
Maybe it's good to know why we should use directives instead of magic strings to reference the template, so i added a interesting StackOverflow answer with reasons 🙂
=> docs(projection): add related link reasons for avoiding magic strings

docs/src/components/ActionButtonFooter.astro, docs/src/components/SubscriptionForm.astro
I guess two buttons have the wrong font color, because there are similar buttons with a different font color:
- landing page of Angular Challenges(https://angular-challenges.vercel.app/) the subscribe button
- all other pages (https://angular-challenges.vercel.app/guides/getting-started/) the sponsor button
=> style: red button unintended font-color black

docs/src/content/docs/challenges/typescript/47-enums-vs-union-types.md
Added a slight note about JavaScript using dynamic typing.  
If you don't like placement or note, I can remove from this commit and just leave the typo fixes.
=> fix: typos enum docs & little extra clarification

docs/src/components/SubscriptionForm.astro, docs/src/styles/custom-css.css
As you mentioned in the closed PR, i've added the hover effect again. I made two other changes as well ...
1. Because the opacity hover effect was barely recognizable, i've changed the hover effect of `opacity: 0.9` to `opacity: 0.85`.
2. We have 3 black icon buttons at the top, which have a hover effect with `opacity: 0.66`. In my opinion that's a good idea, because the hover effects on black buttons are even less noticeable. So i've update the hover effect for black buttons to `opacity: 0.66` as well.
Here is one of the 3 black icon buttons which have that 0.66 opacity already.
---
Do you agree with these changes?
=> style: update button hover effect

docs/src/content/docs/challenges/angular/32-bug-cd.md
Don't know if you want to add or spoil "trackBy" as possible fix so most people don't miss the lesson of this challenge.  I suggest you downvote my bug-cd answers, so people recognize that isn't the correct solution. 
I am not a fan of this line,`If you comment out this line, the application loads again, however the bug is not inside the Angular Framework. 😅😯`, in the hint, as it can be potentially misleading.  The bug is related to how `*ngFor` operates.
=> docs: add note to bug-cd-md

docs/src/content/docs/challenges/angular/1-projection.md
I've noticed that in the first challenge "Projection" the solution buttons are not displayed (Community Solutions & Author's Solution). Close this PR if that's on purpose, if not, here's the fix to show them.
=> fix(docs): missing projection challenge solution buttons

docs/src/content/docs/guides/create-challenge.md
I saw some typos and did some tweaks. Instead of making 2 PRs, I combined it here.  I added a line about using an extension to generate a challenge.   Forms were missing from the list of challenges here as well.
=> fix: create-challenge-typos & extra clarification

docs/src/components/Hero.astro, docs/src/content/config.ts, docs/src/content/i18n/en.json, docs/src/content/i18n/es.json, docs/src/content/i18n/fr.json, docs/src/content/i18n/pt.json, docs/src/content/i18n/ru.json
Hi @tomalaforge. How are you?
It's been a while since my last contribution. Things are a little busy these months :face_exhaling:, but I still wanna help you guys.
Best regards
=> docs: add i18n for hero sponsors banner

docs/src/content/docs/index.mdx
Note: There are 2 `NEW` tags in the sidepanel.  When you merge challenge 51, you can fix that at the same time.
=> fix: latest challenge link 

docs/src/content/docs/guides/checkout-answer.md
I didn't realize you could do this, but for any open PR, you can checkout the answer with GitHub Codespaces.  After any PR closes, you have to use the local method.  
I deleted a commented out command as well.  I don't know it is really necessary or not.
=> docs: checkout answer with codespace

apps/angular/1-projection/src/app/data-access/city.store.ts
Small changes in variable name in addOne method in CityStore. As per context the variable name Should be city instead of student.
=> fix: rename variable name "student" to "city" in addOne method in CityStore

apps/testing/29-real-life-application/src/app/detail/detail.store.ts, apps/testing/29-real-life-application/src/app/list/ticket.store.ts
=> fix(challenge29): fix imports #1339
